"""add daily email tracking

Revision ID: 701d1963984a
Revises: 9c0764f6ba6a
Create Date: 2026-09-27 13:29:56.726952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701d1963984a'
down_revision: Union[str, Sequence[str], None] = '9c0764f6ba6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "daily_email_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "daily_email_date",
            sa.Date(),
            nullable=True,
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_email_date')
    op.drop_column('users', 'daily_email_count')
    # ### end Alembic commands ###
