"""add gmail verification fields

Revision ID: bf7dec2e1515
Revises: 701d1963984a
Create Date: 2026-09-28 20:08:17.648119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7dec2e1515'
down_revision: Union[str, Sequence[str], None] = '701d1963984a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column(
            'gmail_verified',
            sa.Boolean(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE users SET gmail_verified = FALSE WHERE gmail_verified IS NULL"
    )

    op.alter_column(
        'users',
        'gmail_verified',
        nullable=False,
    )

    op.add_column(
        'users',
        sa.Column(
            'gmail_verification_link',
            sa.Text(),
            nullable=True,
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_verification_link')
    op.drop_column('users', 'gmail_verified')
    # ### end Alembic commands ###
